print("Hi! My name is Ishaan Lahoti, and my intials are: ")
print()
print("*******  *")
print("   *     *")
print("   *     *")
print("   *     *")
print("*******  ******")
print()
print("Thanks and bye!")
